name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test tests/e2e/e2e-login.spec.ts --config=e2e.config.ts
      - name: Import results to AgileTest
        if: always()
        run: |
          curl -X POST \
          -u "${{ secrets.JIRA_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}" \
          -H "Accept: application/json" \
          -F "file=@test-results/junit.xml" \
          "${{ secrets.JIRA_BASE_URL }}/rest/atm/1.0/ds/test-executions/junit"
