name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test tests/e2e/e2e-login.spec.ts --config=e2e.config.ts
      - name: Import results to AgileTest
        if: always()
        env:
          AGILETEST_CLIENT_ID: ${{ secrets.AGILETEST_CLIENT_ID }}
          AGILETEST_CLIENT_SECRET: ${{ secrets.AGILETEST_CLIENT_SECRET }}
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          PROJECT_KEY: ${{ secrets.PROJECT_KEY }}
        run: |
          TOKEN=$(curl -s -X POST \
          'https://agiletest.atlas.devsamurai.com/api/apikeys/authenticate' \
          -H 'Content-Type: application/json' \
          -d "{\"clientId\":\"${AGILETEST_CLIENT_ID}\",\"clientSecret\":\"${AGILETEST_CLIENT_SECRET}\"}" \
          | tr -d '"')

          curl -X POST \
          "${JIRA_BASE_URL}/ds/test-executions/junit?projectKey=${PROJECT_KEY}" \
          -H "Content-Type: application/xml" \
          -H "Authorization: JWT ${TOKEN}" \
          --data-binary "@test-results/junit.xml"
